In [61]:
import numpy as np
import math

a = np.random.randint(0, 100, [10, 3])
a

array([[38, 97, 79],
       [56, 34, 51],
       [60, 24, 91],
       [33, 77, 24],
       [25, 59, 66],
       [40, 68, 93],
       [36, 85, 83],
       [99, 10, 23],
       [16, 62, 92],
       [ 2, 51,  6]])

In [62]:
a0 = a[:, 0]
a1 = a[:, 1]
a2 = a[:, 2]
np.resize(np.mean(a0), np.shape(a)[0])
a0-np.resize(np.mean(a0), np.shape(a)[0])


array([ -2.5,  15.5,  19.5,  -7.5, -15.5,  -0.5,  -4.5,  58.5, -24.5,
       -38.5])

In [63]:
np.resize(np.mean(a1), np.shape(a)[0])
a1-np.resize(np.mean(a1), np.shape(a)[0])

array([ 40.3, -22.7, -32.7,  20.3,   2.3,  11.3,  28.3, -46.7,   5.3,
        -5.7])

In [64]:
(a0 - np.resize(np.mean(a0), np.shape(a)[0])) * (a1 - np.resize(np.mean(a1), np.shape(a)[0]))

array([ -100.75,  -351.85,  -637.65,  -152.25,   -35.65,    -5.65,
        -127.35, -2731.95,  -129.85,   219.45])

In [73]:
cov01 = np.sum((a0 - np.resize(np.mean(a0), np.shape(a)[0])) * (a1 - np.resize(np.mean(a1), np.shape(a)[0])))/(np.shape(a)[0]-1)
cov01

-450.3888888888889

In [74]:
cov02 = np.sum((a0 - np.resize(np.mean(a0), np.shape(a)[0])) * (a2 - np.resize(np.mean(a2), np.shape(a)[0])))/(np.shape(a)[0]-1)
cov02

-43.888888888888886

In [75]:
cov21 = np.sum((a2 - np.resize(np.mean(a2), np.shape(a)[0])) * (a1 - np.resize(np.mean(a1), np.shape(a)[0])))/(np.shape(a)[0]-1)
cov21

274.2666666666667

In [76]:
cov00 = np.sum((a0 - np.resize(np.mean(a0), np.shape(a)[0])) * (a0 - np.resize(np.mean(a0), np.shape(a)[0])))/(np.shape(a)[0]-1)
cov00

716.5

In [77]:
cov11 = np.sum((a1 - np.resize(np.mean(a1), np.shape(a)[0])) * (a1 - np.resize(np.mean(a1), np.shape(a)[0])))/(np.shape(a)[0]-1)
cov11

755.1222222222223

In [78]:
cov22 = np.sum((a2 - np.resize(np.mean(a2), np.shape(a)[0])) * (a2 - np.resize(np.mean(a2), np.shape(a)[0])))/(np.shape(a)[0]-1)
cov22

1072.8444444444444

In [79]:
np.cov(a, rowvar=False)

array([[ 716.5       , -450.38888889,  -43.88888889],
       [-450.38888889,  755.12222222,  274.26666667],
       [ -43.88888889,  274.26666667, 1072.84444444]])

In [84]:
a_trans = a - np.resize(np.mean(a, axis=0), [10, 3])
a_trans

array([[ -2.5,  40.3,  18.2],
       [ 15.5, -22.7,  -9.8],
       [ 19.5, -32.7,  30.2],
       [ -7.5,  20.3, -36.8],
       [-15.5,   2.3,   5.2],
       [ -0.5,  11.3,  32.2],
       [ -4.5,  28.3,  22.2],
       [ 58.5, -46.7, -37.8],
       [-24.5,   5.3,  31.2],
       [-38.5,  -5.7, -54.8]])

In [89]:
cov = np.matmul(np.transpose(a_trans), a_trans) / (np.shape(a)[0] - 1)
cov

array([[ 716.5       , -450.38888889,  -43.88888889],
       [-450.38888889,  755.12222222,  274.26666667],
       [ -43.88888889,  274.26666667, 1072.84444444]])

In [ ]:
cov.