In [27]:
import numpy as np
def normalize(train):
    mean, std = train.mean(), train.std()
    train = (train - mean) / std
    return train

x = np.reshape(list(range(0, 20)), [4, 5])
x
# np.shape(x)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
x = normalize(x)
x

array([[-1.64750894, -1.47408695, -1.30066495, -1.12724296, -0.95382097],
       [-0.78039897, -0.60697698, -0.43355498, -0.26013299, -0.086711  ],
       [ 0.086711  ,  0.26013299,  0.43355498,  0.60697698,  0.78039897],
       [ 0.95382097,  1.12724296,  1.30066495,  1.47408695,  1.64750894]])

In [14]:
import tensorflow as tf
y = tf.placeholder(tf.float32, [2, 3], name='input')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    
    y_0 = np.random.randint(1, 20)
    y = sess.run(y, feed_dict={y: y_0})
    print("sdsd", y)
    y_0 = normalize(y_0)
    y = sess.run(y, feed_dict={y: y_0})
    print(y)


ValueError: Cannot feed value of shape () for Tensor 'input_6:0', which has shape '(2, 3)'

In [3]:
import tensorflow as tf
from tensorflow import feature_column as fc

tf.enable_eager_execution()

def categorical_column_with_vocabulary_list():
    color_data = {'color': [['R', 'R'], ['G', 'R'], ['B', 'G'], ['A', 'A']]}  # 4行样本
    color_column = fc.categorical_column_with_vocabulary_list('color', ['R', 'G', 'B'], dtype=tf.string, default_value=-1)
    color_column_identy = fc.indicator_column(color_column)
    color_dense_tensor = fc.input_layer(color_data, [color_column_identy])
    print(color_dense_tensor)
categorical_column_with_vocabulary_list()

tf.Tensor(
[[2. 0. 0.]
 [1. 1. 0.]
 [0. 1. 1.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)
